# Generated by Django 5.0.6 on 2024-11-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('dia_de_trabalho', models.BooleanField(default=False)),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('termino', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
