# Generated by Django 5.1.1 on 2024-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('tempo', models.TimeField(blank=True, null=True)),
                ('preco', models.FloatField(default=0)),
            ],
        ),
    ]
