# Generated by Django 5.1.1 on 2024-11-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='hora_util',
            field=models.FloatField(default=0),
        ),
    ]
