# Generated by Django 5.1.1 on 2024-11-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_horario_hora_util'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_util',
            field=models.CharField(max_length=20),
        ),
    ]
