# Generated by Django 5.1.1 on 2024-11-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_horario_hora_util'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('horario', models.TimeField()),
                ('evento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
