# Generated by Django 5.1.1 on 2024-11-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='evento',
        ),
    ]
