# Generated by Django 5.1.1 on 2024-11-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_remove_agenda_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.IntegerField(),
        ),
    ]
