# Generated by Django 5.1.1 on 2024-11-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_alter_agenda_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='dia_semana',
            field=models.CharField(default='', max_length=60),
        ),
    ]
