# Generated by Django 5.0.6 on 2024-11-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_agenda_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
