# Generated by Django 5.0.6 on 2024-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_agenda_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='hora_disponivel',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
