# Generated by Django 5.1.1 on 2024-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_agenda_hora_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_util',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
